server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ride_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: january123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update           # use 'validate' once you add Flyway/Liquibase
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  jackson:
    time-zone: UTC

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info   # show bound SQL params

jwt:
  issuer: ride-app
  secret: "c2d3f5c9b0e74a1d8f2a3c4b5e6f7081928374655aaabbbcccdddeeefff00112233445566778899aabbccddeeff0011"
  accessTokenMinutes: 60
  refreshTokenDays: 60
  
pricing:
  baseFare: 2.0        # flat fee
  perMile: 0.75          # price per miles
  minimumFare: 5.0     # minimum charge


